version: "3.8"
services:
    backend:
        build:
            context: ./backend
        ports:
            - "5000:5000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
    # db:
    #     build: ./mysql
    #     restart: always
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_DATABASE: bookappdb
    #     ports:
    #         - "3306:3306"
