version: '3'

services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_DATABASE: bookappdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: my-app-user
      MYSQL_PASSWORD: my-app-password
      DATABASE_HOST: mysql
  backend:
    build: ./backend
    environment:
      DATABASE_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: bookappdb
      MYSQL_PORT: 3306
      JWTKEY: qwe123
      SESS_NAME: olololo
      SESS_SECRET: asd321
    depends_on:
      - mysql
    restart: on-failure

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    # ports:
      # - 8080:80

  nginx:
    build:
        context: ./nginx
    ports:
        - "80:80"
    depends_on:
        - backend
    restart: always
