version: '3'

services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_DATABASE: bookappdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: my-app-user
      MYSQL_PASSWORD: my-app-password
      DATABASE_HOST: mysql
  backend:
    build: ./backend
    environment:
      DATABASE_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: bookappdb
      MYSQL_USER: my-app-user
      MYSQL_PASSWORD: my-app-password
      JWTKEY: qwe123
    depends_on:
      - mysql
    restart: on-failure
  nginx:
    build:
        context: ./nginx
    ports:
        - "80:80"
    depends_on:
        - backend
    restart: always
